apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  namespace: default
spec:
  containers:
  - image: nginx
    imagePullPolicy: Always
    name: nginx-pod
    resources:
      limit:
        cpu: 100m
        memory: 200Mi
